[user]
username = "he"
license_key = "MEVARIK-oIGO8U-kdoEj9-cWtytU-sCglKk"

[network]
block_engine_url = "https://amsterdam.mainnet.block-engine.jito.wtf"
pubsub_url = "ws://45.250.254.175:8899/"
rpc_url = "http://45.250.254.175:8899/"
grpc_url = "http://45.250.254.175:10000/"
regions = ["ny"]

[engine]
payer_keypair = ""
subscribe_bundle_results = false
use_bundles = true

[trading]
buy_amount = 0.00001
priority_fee = 0.0001
bundle_tip = 0.00001
slippage = false
spam = false
spam_count = 15
loss_threshold_percentage = -50.0
profit_threshold_percentage = 100.0
copytrade_accounts = [
    "5iywveQKkidqPDKt2CExJcWKex2EXz9kbGcYiZvhuXWs",
    "EP7bbErAipyxFqibUDwkPNrwcsN7zNPoz7o5EoNQM9qd",
    "AZ1wHjhG1v2r87HGKNPcH3sAouAPRVE7W3jpSMzP9Sje",
    "9yMwSPk9mrXSN7yDHUuZurAh1sjbJsfpUqjZ7SvVtdco",
    "Ai9RV1Cxq71DREpzYo9ACdRzBwAAYKtBBULvvcfSbaSP",
]
