[user]
username = "taimurey"
license_key = "MEVARIK-N3SvVm-MYhUfu-goMRao-tUHhTG"

[network]
block_engine_url = "https://ny.mainnet.block-engine.jito.wtf"
pubsub_url = "wss://mainnet.helius-rpc.com/?api-key=0b99078c-7247-47ad-8cf8-35cbfc021667"
rpc_url = "https://mainnet.helius-rpc.com/?api-key=0b99078c-7247-47ad-8cf8-35cbfc021667"
grpc_url = "http://160.202.128.179:10000"
regions = ["ny"]

[engine]
payer_keypair = "4ULY3jziGvx8d3r2K8AmpwYhN4oSAv5FJqNgxiC7ZVtG8Q4e5ksU3tVZFy1wcK1z2Gq24J7zTKFS7iFWmEHhFhtQ"
subscribe_bundle_results = false
use_bundles = false

[trading]
buy_amount = 0.00001
priority_fee = 0.0001
bundle_tip = 0.0001
slippage = false
spam = false
spam_count = 15
copytrade_accounts = [
    "5iywveQKkidqPDKt2CExJcWKex2EXz9kbGcYiZvhuXWs",
    "EP7bbErAipyxFqibUDwkPNrwcsN7zNPoz7o5EoNQM9qd",
    "AZ1wHjhG1v2r87HGKNPcH3sAouAPRVE7W3jpSMzP9Sje",
    "9yMwSPk9mrXSN7yDHUuZurAh1sjbJsfpUqjZ7SvVtdco",
    "Ai9RV1Cxq71DREpzYo9ACdRzBwAAYKtBBULvvcfSbaSP",
]
loss_threshold_percentage = -50.0
profit_threshold_percentage = 100.0
