const JUPITER_ID: Pubkey = pubkey!("JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4");
pub mod accounts;
pub use accounts::*;
pub mod typedefs;
use solana_sdk::pubkey;
use solana_sdk::pubkey::Pubkey;
pub use typedefs::*;
pub mod instructions;
pub use instructions::*;
pub mod errors;
pub use errors::*;
pub mod events;
pub use events::*;
